language: java

addons:
  sonarcloud:
    organization: "alexiscabrol"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=AlexisCabrol_ipi-java-350-tp
